// Generated by CoffeeScript 1.6.3
var cleverStatistics;

cleverStatistics = require('../cleverStatistics');

exports.mean = function(test) {
  test.expect(1);
  return (cleverStatistics('mean')).then(function(stats) {
    test.equal(Math.round(stats.mean), 32);
    return test.done();
  });
};

exports.variadic = function(test) {
  test.expect(1);
  return (cleverStatistics('min', 'max')).then(function(stats) {
    test.deepEqual(stats, {
      min: 19,
      max: 62
    });
    return test.done();
  });
};
