// Generated by CoffeeScript 1.6.3
var Clever, Promise, cleverStatistics;

Clever = require('clever');

Promise = require('when');

cleverStatistics = function() {
  var average, clever, config, deferred, done;
  deferred = Promise.defer();
  config = {
    key: 'DEMO_KEY'
  };
  clever = new Clever(config.key);
  done = function(err, sections) {
    if (err) {
      deferred.reject(Error(err));
    }
    return deferred.resolve(average(sections));
  };
  average = function(sections) {
    var count, sum;
    count = sections.length;
    sum = sections.map(function(section) {
      return (section.toJSON()).students.length;
    }).reduce(function(a, b) {
      return a + b;
    });
    return sum / count;
  };
  clever.Section.find({}, done);
  return deferred.promise;
};

(cleverStatistics()).then(function(stats) {
  return console.log(stats);
}, function(err) {
  return console.error(err);
});
