// Generated by CoffeeScript 1.6.3
var Clever, average, clever, config, done;

Clever = require('clever');

config = {
  key: 'DEMO_KEY'
};

clever = new Clever(config.key);

done = function(err, sections) {
  var mean;
  if (err) {
    throw new Error(err);
  }
  mean = average(sections);
  return console.log(mean);
};

average = function(sections) {
  var count, sum;
  count = sections.length;
  sum = sections.map(function(section) {
    return (section.toJSON()).students.length;
  }).reduce(function(a, b) {
    return a + b;
  });
  return sum / count;
};

clever.Section.find({}, done);
